FROM postgres:18.3
RUN apt-get update \
 && apt-get install --no-install-recommends -y postgresql-18-ip4r \
 && apt-get install --no-install-recommends -y postgresql-18-hll \
 && apt-get install --no-install-recommends -y postgresql-18-pgvector \
 && rm -rf /var/lib/apt/lists/*
COPY docker/init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
