version: '3.4'

x-default_env: &default_env
  environment:
    - DATABASE_USERNAME=es
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
    - REDIS_URL=redis://redis_sidekiq:6379/0/sidekiq
    - REDIS_CACHE_URL=redis://redis_cache:6666/0/cache
    - REDIS_SESSION_STORE_URL=redis://redis_session:6666/0/session
    - REDIS_SIDEKIQ_URL=redis://redis_sidekiq:6379/0/sidekiq
    - MAILER_ADDRESS=mailcatcher
    - MAILER_PORT=1025
    - HOME=/tmp
    - DISPLAY=$DISPLAY
    - SSH_AUTH_SOCK=/tmp/agent.sock


x-default-links: &default_links
  links:
    - redis_cache
    - redis_sidekiq
    - postgres
    - mailcatcher

volumes:
  pgdata12:
  percona57:
  redis:
  redis_cache:

services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    #mem_limit: 8M
    restart: on-failure
  nginx:
    build:
      context: docker
      dockerfile: Dockerfile.nginx-minimal
    ports:
      - "80:80"
    links:
      - dockerhost
  mailcatcher:
    image: precisionnutrition/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  redis_cache:
    image: redis:5
    volumes:
      - redis_cache:/data
    ports:
      - "6666:6379"
  redis_sidekiq:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata12:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 512mb
  percona:
    image: percona/percona-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - percona57:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      PMA_HOST: percona
      PMA_PORT: 3306
