on:
  push: 
    tags:
     - '*'

name: build

jobs:
  # https://github.com/svenstaro/upload-release-action
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-14.04, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pndev
            asset_name: pndev-linux-amd64
          - os: ubuntu-14.04
            artifact_name: pndev
            asset_name: pndev-x86_64-ubuntu-14
          - os: macos-latest
            artifact_name: pndev
            asset_name: pndev-x86_64-apple-darwin

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --locked
    - name: chmod
      run: chmod +x target/release/${{ matrix.artifact_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{github.ref}}
