on:
  push:
    branch:
     - '*'

name: test

jobs:
  test:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pndev
            asset_name: pndev-x86_64-linux
          - os: macos-latest
            artifact_name: pndev
            asset_name: pndev-x86_64-apple-darwin
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: setup
      run: rustup component add clippy rustfmt
    - name: Build
      run: cargo build --release --locked
    - name: clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: fmt
      run: cargo fmt --all -- --check
